import { AssignedFileNames, FileTypes, ProjectFile } from "@/lib/types";
import { v4 as uuidv4 } from "uuid";

export const initialStructure: ProjectFile[] = [
  {
    id: uuidv4(),
    name: AssignedFileNames.src,
    type: FileTypes.directory,
    endpoint: null,
    isExpanded: true,
    isEditable: false,
    isRenameable: false,
    isDeletable: false,
    children: [
      {
        id: uuidv4(),
        name: AssignedFileNames.app,
        type: FileTypes.directory,
        endpoint: "/",
        isExpanded: true,
        isEditable: false,
        isRenameable: false,
        isDeletable: false,
        children: [
          {
            id: uuidv4(),
            name: "dashboard",
            type: FileTypes.directory,
            endpoint: "/dashboard",
            isExpanded: true,
            isEditable: true,
            isRenameable: true,
            isDeletable: true,
            children: [
              {
                id: uuidv4(),
                name: "page.tsx",
                type: FileTypes.page,
                endpoint: "/dashboard",
                isEditable: true,
                isRenameable: false,
                isDeletable: true,
              },
              {
                id: uuidv4(),
                name: "settings",
                type: FileTypes.directory,
                endpoint: "/dashboard/settings",
                isExpanded: true,
                isEditable: true,
                isRenameable: true,
                isDeletable: true,
                children: [
                  {
                    id: uuidv4(),
                    name: "page.tsx",
                    type: FileTypes.page,
                    endpoint: "/dashboard/settings",
                    isEditable: true,
                    isRenameable: false,
                    isDeletable: true,
                  },
                ],
              },
            ],
          },
          {
            id: uuidv4(),
            name: AssignedFileNames.api,
            type: FileTypes.directory,
            endpoint: "/api",
            isExpanded: true,
            isEditable: true,
            isRenameable: false,
            isDeletable: false,
            children: [
              {
                id: uuidv4(),
                name: "route.ts",
                type: FileTypes.route,
                endpoint: "/api",
                isEditable: false,
                isRenameable: false,
                isDeletable: false,
              },
            ],
          },
          {
            id: uuidv4(),
            name: "layout.tsx",
            type: FileTypes.layout,
            endpoint: null,
            isEditable: false,
            isRenameable: false,
            isDeletable: false,
          },
          {
            id: uuidv4(),
            name: "page.tsx",
            type: FileTypes.page,
            endpoint: "/",
            isEditable: false,
            isRenameable: false,
            isDeletable: false,
          },
        ],
      },
      {
        id: uuidv4(),
        name: AssignedFileNames.components,
        type: FileTypes.directory,
        endpoint: null,
        isEditable: false,
        isRenameable: false,
        isDeletable: false,
        children: [
          {
            id: uuidv4(),
            name: "ui",
            type: FileTypes.directory,
            endpoint: null,
            isExpanded: false,
            isEditable: false,
            isRenameable: false,
            isDeletable: false,
            children: [
              {
                id: uuidv4(),
                name: "button.tsx",
                type: FileTypes.file,
                endpoint: null,
                isEditable: false,
                isRenameable: false,
                isDeletable: false,
              },
              {
                id: uuidv4(),
                name: "collapsible.tsx",
                type: FileTypes.file,
                endpoint: null,
                isEditable: false,
                isRenameable: false,
                isDeletable: false,
              },
              {
                id: uuidv4(),
                name: "dialog.tsx",
                type: FileTypes.file,
                endpoint: null,
                isEditable: false,
                isRenameable: false,
                isDeletable: false,
              },
              {
                id: uuidv4(),
                name: "dropdown-menu.tsx",
                type: FileTypes.file,
                endpoint: null,
                isEditable: false,
                isRenameable: false,
                isDeletable: false,
              },
              {
                id: uuidv4(),
                name: "input.tsx",
                type: FileTypes.file,
                endpoint: null,
                isEditable: false,
                isRenameable: false,
                isDeletable: false,
              },
              {
                id: uuidv4(),
                name: "label.tsx",
                type: FileTypes.file,
                endpoint: null,
                isEditable: false,
                isRenameable: false,
                isDeletable: false,
              },
              {
                id: uuidv4(),
                name: "tabs.tsx",
                type: FileTypes.file,
                endpoint: null,
                isEditable: false,
                isRenameable: false,
                isDeletable: false,
              },
            ],
          },
          {
            id: uuidv4(),
            name: "browser-view.tsx",
            type: FileTypes.file,
            endpoint: null,
            isExpanded: false,
            isEditable: false,
            isRenameable: false,
            isDeletable: false,
          },
          {
            id: uuidv4(),
            name: "folder-structure.tsx",
            type: FileTypes.file,
            endpoint: null,
            isExpanded: false,
            isEditable: false,
            isRenameable: false,
            isDeletable: false,
          },
          {
            id: uuidv4(),
            name: "file-node.tsx",
            type: FileTypes.file,
            endpoint: null,
            isExpanded: false,
            isEditable: false,
            isRenameable: false,
            isDeletable: false,
          },
        ],
      },
      {
        id: uuidv4(),
        name: AssignedFileNames.lib,
        type: FileTypes.directory,
        endpoint: null,
        isEditable: false,
        isRenameable: false,
        isDeletable: false,
        children: [
          {
            id: uuidv4(),
            name: "utils.ts",
            type: FileTypes.file,
            endpoint: null,
            isEditable: false,
            isRenameable: false,
            isDeletable: false,
          },
        ],
      },
    ],
  },
  {
    id: uuidv4(),
    name: AssignedFileNames.public,
    type: FileTypes.directory,
    endpoint: null,
    isExpanded: false,
    isEditable: false,
    isRenameable: false,
    isDeletable: false,
    children: [
      {
        id: uuidv4(),
        name: "static",
        type: FileTypes.directory,
        endpoint: null,
        isExpanded: false,
        isEditable: false,
        isRenameable: false,
        isDeletable: false,
        children: [
          {
            id: uuidv4(),
            name: "avatar.jpg",
            type: FileTypes.file,
            endpoint: null,
            isEditable: false,
            isRenameable: false,
            isDeletable: false,
          },
          {
            id: uuidv4(),
            name: "me.png",
            type: FileTypes.file,
            endpoint: null,
            isEditable: false,
            isRenameable: false,
            isDeletable: false,
          },
        ],
      },
      {
        id: uuidv4(),
        name: "favicon.ico",
        type: FileTypes.file,
        endpoint: null,
        isEditable: false,
        isRenameable: false,
        isDeletable: false,
      },
      {
        id: uuidv4(),
        name: "robots.txt",
        type: FileTypes.file,
        endpoint: null,
        isEditable: false,
        isRenameable: false,
        isDeletable: false,
      },
      {
        id: uuidv4(),
        name: "manifest.json",
        type: FileTypes.file,
        endpoint: null,
        isEditable: false,
        isRenameable: false,
        isDeletable: false,
      },
    ],
  },
];
